/* Inter glyphs used by the EVBikes cluster. Generated by tools/gen_assets.py, do not edit by hand. */
#pragma once

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const lv_font_t evb_font_regular_10;
extern const lv_font_t evb_font_regular_11;
extern const lv_font_t evb_font_regular_12;
extern const lv_font_t evb_font_regular_13;
extern const lv_font_t evb_font_regular_14;
extern const lv_font_t evb_font_regular_15;
extern const lv_font_t evb_font_regular_16;
extern const lv_font_t evb_font_regular_17;
extern const lv_font_t evb_font_regular_18;
extern const lv_font_t evb_font_regular_19;
extern const lv_font_t evb_font_regular_20;
extern const lv_font_t evb_font_regular_22;
extern const lv_font_t evb_font_regular_24;
extern const lv_font_t evb_font_regular_26;
extern const lv_font_t evb_font_regular_30;
extern const lv_font_t evb_font_regular_34;
extern const lv_font_t evb_font_italic_11;
extern const lv_font_t evb_font_italic_14;
extern const lv_font_t evb_font_italic_15;
extern const lv_font_t evb_font_italic_16;
extern const lv_font_t evb_font_italic_18;
extern const lv_font_t evb_font_italic_22;
extern const lv_font_t evb_font_bold_10;
extern const lv_font_t evb_font_bold_13;
extern const lv_font_t evb_font_bold_14;
extern const lv_font_t evb_font_bold_16;
extern const lv_font_t evb_font_bold_17;
extern const lv_font_t evb_font_bold_18;
extern const lv_font_t evb_font_bold_20;
extern const lv_font_t evb_font_bold_24;
extern const lv_font_t evb_font_bold_30;
extern const lv_font_t evb_font_bold_italic_12;
extern const lv_font_t evb_font_bold_italic_16;
extern const lv_font_t evb_font_bold_italic_19;
extern const lv_font_t evb_font_bold_italic_20;
extern const lv_font_t evb_font_bold_italic_22;
extern const lv_font_t evb_font_bold_italic_26;
extern const lv_font_t evb_font_bold_italic_30;
extern const lv_font_t evb_font_logo_64;

#ifdef __cplusplus
}
#endif
